version: "2.0"

services:
  ######################################################################
  # example of using docker data container to manage pmm-server data
  ######################################################################
  # pmm-data:
  #   image: percona/pmm-server
  #   container_name: pmm-data
  #   volumes:
  #     - /opt/prometheus/data
  #     - /opt/consul-data
  #     - /var/lib/mysql
  #     - /var/lib/grafana
  #   entrypoint: /bin/true

  pmm-server:
    container_name: pmm-server
    image: percona/pmm-server:2.5.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "pmm_prometheus_data:/opt/prometheus/data"
      - "pmm_consul_data:/opt/consul-data"
      - "pmm_grafana_data:/var/lib/grafana"
    environment:
      - METRICS_RETENTION=720h
      - METRICS_MEMORY=262144
      - METRICS_RESOLUTION=1s
      - QUERIES_RETENTION=8
      - SERVER_USER=admin
      - SERVER_PASSWORD=password

volumes:
  pmm_prometheus_data: {}
  pmm_consul_data: {}
  pmm_grafana_data: {}

networks:
  default:
    external:
      name: bitnami_approach_mongo
