# let ansible gather info on all mongodb nodes first before running any automation
- hosts: mongodb_cluster
  gather_facts: True
  gather_subset: [network, hardware]
  tasks: []

- hosts: pmm_server
  gather_facts: False
  roles:
    - pmm-server
#
# - hosts: config_servers
#   gather_facts: False
#   serial: 1 # rolling update instead of parallel automate every config servers
#   roles:
#     - mongo-cfgsvr
#
- hosts: mongos
  gather_facts: False
  serial: 1 # rolling update instead of parallel automate every config servers
  roles:
    - mongos
#
# - hosts: mongo_shards
#   serial: 1 # rolling update instead of parallel automate every config servers
#   roles:
#     - mongo-shard
