- name: add offline docker yum repo
  yum_repository:
    name: offline-docker-ce-stable
    description: Docker CE packages from official repo made offline
    baseurl: "{{ yum.docker.repo_url }}"
    file: offline-docker-ce
    gpgcheck: no
    sslverify: no
    enabled: yes
  become: yes
